### ISSUE TITLE
Report: "RuntimeError: deque mutated during iteration"

### ISSUE THREAD

**Issue by crwood** [gridsync/gridsync#249]
An anonymous tester writes:

>Crashed trying to open debug log:
>
>```
>Traceback (most recent call last):
>  File "gridsync/gui/debug.py", line 94, in load
>  File "gridsync/tahoe.py", line 484, in get_log
>  File "gridsync/streamedlogs.py", line 81, in get_streamed_log_messages
>  File "gridsync/streamedlogs.py", line 81, in <genexpr>
>RuntimeError: deque mutated during iteration
>```

**Comment by crwood** [comment]
Re-opening; see https://github.com/gridsync/gridsync/pull/250#discussion_r311981445
