### ISSUE TITLE
[install] ImportError: No module named PyQt5.QtWidgets

### ISSUE THREAD

**Issue by arthurlutz** [gridsync/gridsync#40]
After following the install instructions I get : 

```
$ gridsync
Traceback (most recent call last):
  File "/home/arthur/.virtualenvs/gridsync/bin/gridsync", line 11, in <module>
    load_entry_point('gridsync==0.0.1', 'console_scripts', 'gridsync')()
  File "/home/arthur/.virtualenvs/gridsync/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/arthur/.virtualenvs/gridsync/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2589, in load_entry_point
    return ep.load()
  File "/home/arthur/.virtualenvs/gridsync/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2249, in load
    return self.resolve()
  File "/home/arthur/.virtualenvs/gridsync/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2255, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/arthur/.virtualenvs/gridsync/local/lib/python2.7/site-packages/gridsync/cli.py", line 13, in <module>
    from gridsync.core import Core
  File "/home/arthur/.virtualenvs/gridsync/local/lib/python2.7/site-packages/gridsync/core.py", line 7, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: No module named PyQt5.QtWidgets
```

What did I miss or do wrong ?

**Comment by arthurlutz** [comment]
Sorry, I didn't see the ```--system-site-packages```

```toggleglobalsitepackages``` in virtualenvwrapper fixed this.
