### ISSUE TITLE
32-bit

### ISSUE THREAD

**Issue by equim** [gridsync/gridsync#45]
I tried the linux 0.1.0 release which didn't work as it is 64-bit whereas my machine is 32-bit x86.

I also tried the build from source instructions which unfortunately failed as pyqt5 doesn't have a 32-bit package on pypi.  I imagine that this will make it hard to provide 32-bit linux builds but it would be good to at least make it clear that 32-bit linux is not supported, e.g. by changing the release filenames and adding a note in the build from source instructions.

**Comment by crwood** [comment]
Hi there. Thanks for reaching out -- and sorry to hear the source-based installation instructions didn't work on your 32-bit machine. You're certainly right that the current lack of 32-bit support should be made more explicit and I'll be sure to update things accordingly for the next release.

In the meantime, do you recall whether PyQt5 was the only dependency that failed to provide a 32-bit compatible package when you tried installing from source? If so, I'm wondering whether it might be possible to get around the issue (at least for now) by installing the required (32-bit) dependencies using your distro's package-manager and then modifying the installation procedure to use those packages instead of the ones from PyPI.. On Debian-based distros, this should consist in manually installing the `python3-pyqt5` and `python3-pyqt5.qtsvg` packages, creating the python3 virtualenv with the `--system-site-packages` flag, and then skipping over the step of having `pip` install from the "requirements" file -- like so:

```
sudo apt-get install virtualenv build-essential python-dev libssl-dev libffi-dev python3.5-dev python3-pyqt5 python3-pyqt5.qtsvg
virtualenv --python=python2 ./venv2
./venv2/bin/pip install --upgrade setuptools pip
./venv2/bin/pip install tahoe-lafs
virtualenv --python=python3.5 --system-site-packages ./venv3
./venv3/bin/pip install --upgrade setuptools pip
./venv3/bin/pip install .
PATH=$PATH:./venv2/bin ./venv3/bin/gridsync
```

I've gone ahead and updated the project's `setup.py` with a quick hack to drop the hard PyQt5 requirement for 32-bit Linux (while still throwing an error if it isn't already installed/importable) so the above steps _should_ work if PyQt5 was the only package that failed.. In any case, if do you try it, please let me know if it works and I will add the modified steps to the docs as a holdover for now (or try to figure out another approach if it doesn't..).

Thanks again for opening the Issue!

**Comment by equim** [comment]
The new instructions work with master - thanks!

When running `PATH=$PATH:./venv2/bin ./venv3/bin/gridsync` I got the following:
```
Traceback (most recent call last):
  File "/home/equim/opt/gridsync/venv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/home/equim/opt/gridsync/venv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/equim/opt/gridsync/venv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (idna 2.0 (/usr/lib/python3/dist-packages), Requirement.parse('idna>=2.1'), {'cryptography'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./venv3/bin/gridsync", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/equim/opt/gridsync/venv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/home/equim/opt/gridsync/venv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/home/equim/opt/gridsync/venv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/equim/opt/gridsync/venv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/equim/opt/gridsync/venv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/equim/opt/gridsync/venv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (idna 2.0 (/usr/lib/python3/dist-packages), Requirement.parse('idna>=2.1'), {'cryptography'})
```

or occasionally:
```
Traceback (most recent call last):
  File "/home/equim/opt/gridsync/venv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/home/equim/opt/gridsync/venv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/equim/opt/gridsync/venv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyasn1 0.1.9 (/usr/lib/python3/dist-packages), Requirement.parse('pyasn1<0.4.0,>=0.3.4'), {'pyasn1-modules'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./venv3/bin/gridsync", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/equim/opt/gridsync/venv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/home/equim/opt/gridsync/venv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/home/equim/opt/gridsync/venv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/equim/opt/gridsync/venv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/equim/opt/gridsync/venv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/equim/opt/gridsync/venv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyasn1 0.1.9 (/usr/lib/python3/dist-packages), Requirement.parse('pyasn1<0.4.0,>=0.3.4'), {'pyasn1-modules'})
```

Can't say I really understand what's going on there but it sounds to me like my distro (Ubuntu 16.04.3 LTS) has a broken default python3 environment?  Anyway, I upgraded those two packages using:
```
sudo pip3 install idna --upgrade
sudo pip3 install pyasn1 --upgrade
```
and then gridsync worked.
