### ISSUE TITLE
"ImportError: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: drmGetDevices2"

### ISSUE THREAD

**Issue by crwood** [gridsync/gridsync#47]
An anonymous user reports that the Gridsync 0.2 binary bundle is failing to launch on Ubuntu 17.10 with the following output: 

```$ ./gridsync 
Traceback (most recent call last): 
File "gridsync/cli.py", line 13, in <module> 
File "/home/travis/build/gridsync/gridsync/build/venv-gridsync/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module 
File "gridsync/core.py", line 7, in <module> 
File "/home/travis/build/gridsync/gridsync/build/venv-gridsync/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module 
ImportError: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: drmGetDevices2
```

**Comment by crwood** [comment]
Similar to #43, this can be resolved by removing the offending bundled library -- in this case, `libdrm.so.2` -- from the extracted Gridsync directory and re-running the application (after which point the PyInstaller "bootloader" will attempt to load the system-installed version and launch successfully).

To be resolved by #48
