### ISSUE TITLE
Autobahn version 22.5.1 breaks Windows integration tests

### ISSUE THREAD

**Issue by crwood** [gridsync/gridsync#479]
After updating autobahn from version 22.4.2 to version 22.5.1, [Windows integration tests break on GitHub Actions](https://github.com/gridsync/gridsync/runs/6727976876?check_suite_focus=true#step%3A8%3A17=):

```
integration create: D:\a\gridsync\gridsync\.tox\integration
integration installdeps: -rD:\a\gridsync\gridsync/requirements/gridsync.txt, -rD:\a\gridsync\gridsync/requirements/pyqt6.txt, -rD:\a\gridsync\gridsync/requirements/test.txt
integration develop-inst: D:\a\gridsync\gridsync
integration installed: atomicwrites==1.4.0,attrs==21.4.0,autobahn==22.5.1,Automat==20.2.0,certifi==2022.5.18.1,cffi==1.15.0,charset-normalizer==2.0.12,click==8.1.3,colorama==0.4.4,constantly==15.1.0,coverage==6.4,cryptography==37.0.2,decorator==5.1.1,greenlet==1.1.2,-e git+https://github.com/gridsync/gridsync@b1384ca3408e869600a85d80d3da14bf29ad8d91#egg=gridsync,hkdf==0.0.3,humanize==4.1.0,hyperlink==21.0.0,idna==3.3,incremental==21.3.0,iniconfig==1.1.1,magic-wormhole==0.12.0,packaging==21.3,pluggy==1.0.0,psutil==5.9.1,py==1.11.0,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycparser==2.21,PyNaCl==1.5.0,pyOpenSSL==22.0.0,pyparsing==3.0.9,PyQt6==6.3.0,PyQt6-Charts==6.3.0,PyQt6-Charts-Qt6==6.3.0,PyQt6-Qt6==6.3.0,PyQt6-sip==13.3.1,pytest==7.1.2,pytest-cov==3.0.0,pytest-qt==4.0.2,pytest-twisted==1.13.4,pytest-xvfb==2.0.0,PyVirtualDisplay==3.0,pywin32==304,PyYAML==6.0,QtPy==2.1.0,requests==2.27.1,service-identity==21.1.0,six==1.16.0,spake2==0.8,tomli==2.0.1,tqdm==4.64.0,treq==22.2.0,Twisted==22.4.0,twisted-iocpsupport==1.0.2,txaio==22.2.1,txtorcon==22.0.0,typing_extensions==4.2.0,urllib3==1.26.9,watchdog==2.1.8,zope.interface==5.4.0,zxcvbn==4.4.28
integration run-test-pre: PYTHONHASHSEED='484'
integration run-test: commands[0] | python -m pytest tests/integration
<frozen importlib._bootstrap>:97: ResourceWarning: unclosed <socket.socket fd=688, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 61703), raddr=('127.0.0.1', 61702)>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
<frozen importlib._bootstrap>:97: ResourceWarning: unclosed <socket.socket fd=692, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 61702), raddr=('127.0.0.1', 61703)>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "D:\a\gridsync\gridsync\.tox\integration\lib\site-packages\_pytest\main.py", line 264, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "D:\a\gridsync\gridsync\.tox\integration\lib\site-packages\_pytest\config\__init__.py", line 995, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "D:\a\gridsync\gridsync\.tox\integration\lib\site-packages\pluggy\_hooks.py", line 277, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
INTERNALERROR>   File "D:\a\gridsync\gridsync\.tox\integration\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "D:\a\gridsync\gridsync\.tox\integration\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "D:\a\gridsync\gridsync\.tox\integration\lib\site-packages\pluggy\_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "D:\a\gridsync\gridsync\.tox\integration\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "D:\a\gridsync\gridsync\.tox\integration\lib\site-packages\_pytest\debugging.py", line 68, in pytest_configure
INTERNALERROR>     import pdb
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 1004, in _find_and_load
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 158, in __enter__
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 110, in acquire
INTERNALERROR> KeyError: 1764
ERROR: InvocationError for command 'D:\a\gridsync\gridsync\.tox\integration\Scripts\python.EXE' -m pytest tests/integration (exited with code 3)
___________________________________ summary ___________________________________
ERROR:   integration: commands failed
```

More investigation is required...

**Comment by crwood** [comment]
A similar, but not identical, error was observed (and reproduced multiple times) in 1653f17486e22179bb0835f7f98fc0410438adbc ([logs](https://github.com/gridsync/gridsync/runs/6780208577?check_suite_focus=true#step%3A8%3A16=)):

```
Run .\make.bat test-integration
  .\make.bat test-integration
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    QT_API: pyqt5
integration create: D:\a\gridsync\gridsync\.tox\integration
integration installdeps: -rD:\a\gridsync\gridsync/requirements/gridsync.txt, -rD:\a\gridsync\gridsync/requirements/pyqt5.txt, -rD:\a\gridsync\gridsync/requirements/test.txt
integration develop-inst: D:\a\gridsync\gridsync
integration installed: atomicwrites==1.4.0,attrs==21.4.0,autobahn==22.4.2,Automat==20.2.0,certifi==2022.5.18.1,cffi==1.15.0,charset-normalizer==2.0.12,click==8.1.3,colorama==0.4.4,constantly==15.1.0,coverage==6.4.1,cryptography==37.0.2,decorator==5.1.1,greenlet==1.1.2,-e git+https://github.com/gridsync/gridsync@9bafeb0a13f79ed6e0cc0eeecb44f4dcf22df519#egg=gridsync,hkdf==0.0.3,humanize==4.1.0,hyperlink==21.0.0,idna==3.3,incremental==21.3.0,iniconfig==1.1.1,magic-wormhole==0.12.0,packaging==21.3,pluggy==1.0.0,psutil==5.9.1,py==1.11.0,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycparser==2.21,PyNaCl==1.5.0,pyOpenSSL==22.0.0,pyparsing==3.0.9,PyQt5==5.15.6,PyQt5-Qt5==5.15.2,PyQt5-sip==12.10.1,PyQtChart==5.15.5,PyQtChart-Qt5==5.15.2,pytest==7.1.2,pytest-cov==3.0.0,pytest-qt==4.0.2,pytest-twisted==1.13.4,pytest-xvfb==2.0.0,PyVirtualDisplay==3.0,pywin32==304,PyYAML==6.0,QtPy==2.1.0,requests==2.27.1,service-identity==21.1.0,six==1.16.0,spake2==0.8,tomli==2.0.1,tqdm==4.64.0,treq==22.2.0,Twisted==22.4.0,twisted-iocpsupport==1.0.2,txaio==22.2.1,txtorcon==22.0.0,typing_extensions==4.2.0,urllib3==1.26.9,watchdog==2.1.8,zope.interface==5.4.0,zxcvbn==4.4.28
integration run-test-pre: PYTHONHASHSEED='57'
integration run-test: commands[0] | python -m pytest tests/integration
<frozen importlib._bootstrap>:97: ResourceWarning: unclosed <socket.socket fd=756, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 50298), raddr=('127.0.0.1', 50297)>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
<frozen importlib._bootstrap>:97: ResourceWarning: unclosed <socket.socket fd=1028, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 50297), raddr=('127.0.0.1', 50298)>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "D:\a\gridsync\gridsync\.tox\integration\lib\site-packages\_pytest\main.py", line 264, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "D:\a\gridsync\gridsync\.tox\integration\lib\site-packages\_pytest\config\__init__.py", line 995, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "D:\a\gridsync\gridsync\.tox\integration\lib\site-packages\pluggy\_hooks.py", line 277, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
INTERNALERROR>   File "D:\a\gridsync\gridsync\.tox\integration\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "D:\a\gridsync\gridsync\.tox\integration\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "D:\a\gridsync\gridsync\.tox\integration\lib\site-packages\pluggy\_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "D:\a\gridsync\gridsync\.tox\integration\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "D:\a\gridsync\gridsync\.tox\integration\lib\site-packages\pytestqt\plugin.py", line 203, in pytest_configure
INTERNALERROR>     qt_api.set_qt_api(config.getini("qt_api"))
INTERNALERROR>   File "D:\a\gridsync\gridsync\.tox\integration\lib\site-packages\pytestqt\qt_compat.py", line 75, in set_qt_api
INTERNALERROR>     self.pytest_qt_api = self._get_qt_api_from_env() or api or self._guess_qt_api()
INTERNALERROR>   File "D:\a\gridsync\gridsync\.tox\integration\lib\site-packages\pytestqt\qt_compat.py", line 64, in _guess_qt_api
INTERNALERROR>     if _can_import("PySide6.QtCore"):
INTERNALERROR>   File "D:\a\gridsync\gridsync\.tox\integration\lib\site-packages\pytestqt\qt_compat.py", line 56, in _can_import
INTERNALERROR>     _import(name)
INTERNALERROR>   File "D:\a\gridsync\gridsync\.tox\integration\lib\site-packages\pytestqt\qt_compat.py", line 23, in _import
INTERNALERROR>     return __import__(name)
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 1004, in _find_and_load
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 158, in __enter__
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 110, in acquire
INTERNALERROR> KeyError: 932
ERROR: InvocationError for command 'D:\a\gridsync\gridsync\.tox\integration\Scripts\python.EXE' -m pytest tests/integration (exited with code 3)
___________________________________ summary ___________________________________
ERROR:   integration: commands failed
Error in batch file; exiting with error level 1
Error: Process completed with exit code 1.
```

I was able to reproduce this issue locally on a Windows 10 VM. Some things we seem to know/learned:
* The issue does not appear to be tied to any specific versions of any particular dependencies, but rather, to specific revisions/commits for other reasons; the issue can be reproduced by checking out 1653f17486e22179bb0835f7f98fc0410438adbc (on Windows) from the Gridsync source tree and running `make.bat clean`, `make.bat test`, `make.bat pyinstaller` and `make.bat test-integration` (in that order), however, revisions other/later than those -- _even which contain the exact same code_ -- may not exhibit the same issue.
* If we disable the non-integration tests (currently declared by the `py39` and `lint` tox test envs) on CI _or_ run the integration tests _before_ the non-integration tests, the issue does not occur. This seems to suggest that some state or environmental factors are carrying over from the non-integration tests to the integration tests.
* Setting `PYTHONDONTWRITEBYTECODE=1` (from an unclean working tree, _without_ git committing the change) on Windows appears to resolve the issue (while setting `PYTHONDONTWRITEBYTECODA=1` did not, possibly ruling out environment size as the factor).
* There may be a thread re-entrancy issue [here](https://github.com/python/cpython/blob/v3.9.13/Lib/importlib/_bootstrap.py#L110) in the standard library, accounting for the `KeyError` above. It's not yet clear where/how pytest is using threads in such a way that might trigger it, however...

**Comment by exarkun** [comment]
Further investigation points pretty directly at https://github.com/python/cpython/issues/91351 as the underlying cause.  There is now a pull request against CPython which may fix that bug: https://github.com/python/cpython/pull/94342 (though in who-knows-what version of CPython).

With this understanding of the cause, some other mitigations become apparent.  We could disable garbage collection.  We could disable ResourceWarnings.  We could pre-import the relevant modules.

Of these, disabling ResourceWarnings seems like the most appealing to me.  However, I'm a little confused about why ResourceWarnings are enabled in these environments at all.  I can't see why the default would be to show them and I can't see anything in GridSync's CI configuration that changes that default.

Am I missing something?

**Comment by crwood** [comment]
>Of these, disabling ResourceWarnings seems like the most appealing to me. However, I'm a little confused about why ResourceWarnings are enabled in these environments at all. I can't see why the default would be to show them and I can't see anything in GridSync's CI configuration that changes that default.
>
>Am I missing something?

I'm confused by this too. According to [the docs](https://docs.python.org/3.9/library/warnings.html#default-warning-filter), ResourceWarnings are supposed to be disabled by default _with the exception of debug builds_:

>In regular release builds, the default warning filter has the following entries (in order of precedence):
>
>```default::DeprecationWarning:__main__
>ignore::DeprecationWarning
>ignore::PendingDeprecationWarning
>ignore::ImportWarning
>ignore::ResourceWarning
>```
>In debug builds, the list of default warning filters is empty.

Perhaps GHA is using debug builds then? How can we tell?

(FWIW, `PYTHONWARNINGS` isn't set on GHA either...)

**Comment by crwood** [comment]
> `sys.flags.debug` will tell us, I think.

[Here's the output of `sys.flags` on GHA](https://github.com/gridsync/gridsync/runs/7083089340?check_suite_focus=true#step%3A5%3A8=):

>`sys.flags(debug=0, inspect=0, interactive=0, optimize=0, dont_write_bytecode=0, no_user_site=0, no_site=0, ignore_environment=0, verbose=0, bytes_warning=0, quiet=0, hash_randomization=1, isolated=0, dev_mode=False, utf8_mode=0, warn_default_encoding=0)`

After digging around the environment for a bit, it looks like they're being switched on by pytest. According to [the docs](https://docs.pytest.org/en/stable/how-to/capture-warnings.html):

>Starting from version 3.1, pytest now automatically catches warnings during test execution and displays them at the end of the session

**Comment by exarkun** [comment]
The CPython bug fixed was merged.  So expect this to be resolved in Python 3.12, I suppose?  I don't know if anyone will backport it or not.
