### ISSUE TITLE
Gridsync crashes upon voucher redemption with a grid configured to issue 150K tokens per voucher

### ISSUE THREAD

**Issue by jehadbaeth** [gridsync/gridsync#532]
Gridsync crashes upon voucher redemption with a grid configured to issue 150K tokens per voucher

```
2022-08-18T13:28:25.908653+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:25+0300 [twisted.python.log#info] web: 127.0.0.1 GET /?t=json 200 1067
2022-08-18T13:28:26.542883+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:26+0300 [_zkapauthorizer.controller.RistrettoRedeemer#info] Redeemed: ucIvmYxTqAl8TFMO4R1svNE7v37dHegWENL0SZIlsQBK160/NwlFZJhsG766tCQnD3yEkexJmatvjzF2f2aXAw== 9375
2022-08-18T13:28:26.542971+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:26+0300 [_zkapauthorizer.controller.RistrettoRedeemer#info] Decoded public key
2022-08-18T13:28:26.553013+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:26+0300 [_zkapauthorizer.controller.RistrettoRedeemer#info] Decoded signed tokens
2022-08-18T13:28:26.553075+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:26+0300 [_zkapauthorizer.controller.RistrettoRedeemer#info] Decoded batch proof
2022-08-18T13:28:27.419037+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:27+0300 [_zkapauthorizer.controller.RistrettoRedeemer#info] Validated proof
2022-08-18T13:28:27.440407+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:27+0300 [_zkapauthorizer.controller.PaymentController#info] Inserting redeemed unblinded tokens for a voucher (b'VBCh2XiNDT2yV8W4SiBLSviVgGvXehhF29lCWyOTpIcf').
2022-08-18T13:28:27.440525+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:27+0300 [_zkapauthorizer.model.VoucherStore#info] Recording 9375 spendable unblinded tokens from public key .
2022-08-18T13:28:27.589499+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:27+0300 [_zkapauthorizer.controller.PaymentController#info] Generating random tokens for a voucher (b'VBCh2XiNDT2yV8W4SiBLSviVgGvXehhF29lCWyOTpIcf').
2022-08-18T13:28:27.631455+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:27+0300 [_zkapauthorizer.model.VoucherStore#info] Persisting 9375 random tokens for a voucher (VBCh2XiNDT2yV8W4SiBLSviVgGvXehhF29lCWyOTpIcf[10]).
2022-08-18T13:28:27.821547+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:27+0300 [_zkapauthorizer.controller.PaymentController#info] Redeeming random tokens for a voucher (Voucher(number=b'VBCh2XiNDT2yV8W4SiBLSviVgGvXehhF29lCWyOTpIcf', expected_tokens=150000, created=datetime.datetime(2022, 8, 18, 16, 27, 41, 188398), state=Pending(counter=10))).
2022-08-18T13:28:28.416469+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:28+0300 [twisted.web.client._HTTP11ClientFactory#info] Stopping factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7f3f823c6320>, <twisted.internet.endpoints._WrapperEndpoint object at 0x7f3f6f983040>)
2022-08-18T13:28:28.417184+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:28+0300 [twisted.python.log#info] web: 127.0.0.1 GET /storage-plugins/privatestorageio-zkapauthz-v1/voucher 200 244
2022-08-18T13:28:28.417321+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:28+0300 [twisted.web.client._HTTP11ClientFactory#info] Starting factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7f3f823c4040>, <twisted.internet.endpoints._WrapperEndpoint object at 0x7f3f6ee8f370>)
2022-08-18T13:28:28.460190+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:28+0300 [twisted.python.log#info] web: 127.0.0.1 GET /storage-plugins/privatestorageio-zkapauthz-v1/unblinded-token?limit=1 200 226
2022-08-18T13:28:28.460947+00:00 DEBUG emit_zkaps_updated ZKAPs updated: used: 0, remaining: 93747; cumulative total: 93747, trimmed total: 93747 (batch size: 150000, batches consumed: 0; tokens deducted: 0)
2022-08-18T13:28:28.509498+00:00 DEBUG poll Connected to "HRO Cloud"
2022-08-18T13:28:28.510018+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:28+0300 [twisted.python.log#info] web: 127.0.0.1 GET / 200 12563
2022-08-18T13:28:28.510055+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:28+0300 [twisted.python.log#info] web: 127.0.0.1 GET /?t=json 200 1067
2022-08-18T13:28:28.586089+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:28+0300 [twisted.python.log#info] web: 127.0.0.1 GET /uri/[CENSORED]?t=json 200 386
2022-08-18T13:28:28.586999+00:00 DEBUG on_stdout_line_received [magic-folder:stdout] 2022-08-18T16:28:28+0300 "127.0.0.1" - - [18/Aug/2022:13:28:28 +0000] "GET /v1/magic-folder?include_secret_information=1 HTTP/1.1" 200 2 "-" "-"
2022-08-18T13:28:28.588579+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:28+0300 [twisted.python.log#info] web: 127.0.0.1 POST /storage-plugins/privatestorageio-zkapauthz-v1/calculate-price 200 31
2022-08-18T13:28:28.970649+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:28+0300 [twisted.python.log#info] web: 127.0.0.1 GET /?t=json 200 1067
2022-08-18T13:28:29.868453+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:29+0300 [twisted.python.log#info] web: 127.0.0.1 GET /storage-plugins/privatestorageio-zkapauthz-v1/voucher 200 244
2022-08-18T13:28:29.910749+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:29+0300 [twisted.python.log#info] web: 127.0.0.1 GET /storage-plugins/privatestorageio-zkapauthz-v1/unblinded-token?limit=1 200 226
2022-08-18T13:28:29.912709+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:29+0300 [twisted.python.log#info] web: 127.0.0.1 GET /?t=json 200 1067
2022-08-18T13:28:31.234162+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:31+0300 [_zkapauthorizer.controller.RistrettoRedeemer#info] Redeemed:  6iXL+PCLzav4+j3RN1C06j3JSmoU2CA8eJFBF7D3XgvsENxCSIjA+iaOV6FH3QyFy+iEoE4qKI/Nc3ZG1JWWCA== 9375
2022-08-18T13:28:31.234214+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:31+0300 [_zkapauthorizer.controller.RistrettoRedeemer#info] Decoded public key
2022-08-18T13:28:31.244164+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:31+0300 [_zkapauthorizer.controller.RistrettoRedeemer#info] Decoded signed tokens
2022-08-18T13:28:31.244228+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:31+0300 [_zkapauthorizer.controller.RistrettoRedeemer#info] Decoded batch proof
2022-08-18T13:28:32.108950+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:32+0300 [_zkapauthorizer.controller.RistrettoRedeemer#info] Validated proof
2022-08-18T13:28:32.171128+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:32+0300 [_zkapauthorizer.controller.PaymentController#info] Inserting redeemed unblinded tokens for a voucher (b'VBCh2XiNDT2yV8W4SiBLSviVgGvXehhF29lCWyOTpIcf').
2022-08-18T13:28:32.171230+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:32+0300 [_zkapauthorizer.model.VoucherStore#info] Recording 9375 spendable unblinded tokens from public key .
2022-08-18T13:28:32.330573+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:32+0300 [_zkapauthorizer.controller.PaymentController#info] Generating random tokens for a voucher (b'VBCh2XiNDT2yV8W4SiBLSviVgGvXehhF29lCWyOTpIcf').
2022-08-18T13:28:32.372624+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:32+0300 [_zkapauthorizer.model.VoucherStore#info] Persisting 9375 random tokens for a voucher (VBCh2XiNDT2yV8W4SiBLSviVgGvXehhF29lCWyOTpIcf[11]).
2022-08-18T13:28:32.531068+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:32+0300 [_zkapauthorizer.controller.PaymentController#info] Redeeming random tokens for a voucher (Voucher(number=b'VBCh2XiNDT2yV8W4SiBLSviVgGvXehhF29lCWyOTpIcf', expected_tokens=150000, created=datetime.datetime(2022, 8, 18, 16, 27, 41, 188398), state=Pending(counter=11))).
2022-08-18T13:28:33.124858+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:33+0300 [twisted.web.client._HTTP11ClientFactory#info] Stopping factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7f3f823c4040>, <twisted.internet.endpoints._WrapperEndpoint object at 0x7f3f6ee8f370>)
2022-08-18T13:28:33.125586+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:33+0300 [twisted.python.log#info] web: 127.0.0.1 GET /storage-plugins/privatestorageio-zkapauthz-v1/voucher 200 244
2022-08-18T13:28:33.125729+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:33+0300 [twisted.web.client._HTTP11ClientFactory#info] Starting factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7f3f823c6560>, <twisted.internet.endpoints._WrapperEndpoint object at 0x7f3f7c263610>)
2022-08-18T13:28:33.172695+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:33+0300 [twisted.python.log#info] web: 127.0.0.1 GET /storage-plugins/privatestorageio-zkapauthz-v1/unblinded-token?limit=1 200 228
2022-08-18T13:28:33.173464+00:00 DEBUG emit_zkaps_updated ZKAPs updated: used: 0, remaining: 103122; cumulative total: 103122, trimmed total: 103122 (batch size: 150000, batches consumed: 0; tokens deducted: 0)
2022-08-18T13:28:33.193974+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:33+0300 [twisted.python.log#info] web: 127.0.0.1 GET / 200 12572
2022-08-18T13:28:33.203330+00:00 DEBUG poll Connected to "HRO Cloud"
2022-08-18T13:28:33.204887+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:33+0300 [twisted.python.log#info] web: 127.0.0.1 GET /?t=json 200 1067
2022-08-18T13:28:33.277706+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:33+0300 [twisted.python.log#info] web: 127.0.0.1 GET /uri/[CENSORED]?t=json 200 386
2022-08-18T13:28:33.278620+00:00 DEBUG on_stdout_line_received [magic-folder:stdout] 2022-08-18T16:28:33+0300 "127.0.0.1" - - [18/Aug/2022:13:28:32 +0000] "GET /v1/magic-folder?include_secret_information=1 HTTP/1.1" 200 2 "-" "-"
2022-08-18T13:28:33.280181+00:00 DEBUG line_received [HRO Cloud] >>> 2022-08-18T16:28:33+0300 [twisted.python.log#info] web: 127.0.0.1 POST /storage-plugins/privatestorageio-zkapauthz-v1/calculate-price 200 31
Traceback (most recent call last):
  File "twisted/internet/defer.py", line 1660, in _inlineCallbacks
StopIteration: {'price': 1, 'period': 2678400}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "twisted/internet/defer.py", line 1660, in _inlineCallbacks
StopIteration: {'price': 1, 'period': 2678400}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gridsync/gui/status.py", line 241, in on_days_remaining_updated
OverflowError: date value out of range
Aborted (core dumped)
```

**Comment by crwood** [comment]
Thanks for reporting this. 

Like in #78, this crash appears to be caused by [mixing/converting between Qt's C++ integers (which overflow) and python's `int`s (which do not overflow)](https://github.com/gridsync/gridsync/issues/78#issuecomment-380175597)

Changing [this `Slot` decorator]( https://github.com/gridsync/gridsync/blob/28ecf7f2b99e93b6a5b7256af48e97ba9ebbdcfc/gridsync/gui/status.py#L237) to take an `object` instead of an `int` should fix this.
