### ISSUE TITLE
Latest version of PyInstaller breaks Windows builds on GitHub Actions

### ISSUE THREAD

**Issue by crwood** [gridsync/gridsync#561]
After updating PyInstaller from version 5.3 to 5.4.1, the resultant Tahoe-LAFS binary fails to execute, [terminating with an exit code of 1 but with no discernible error messages](https://github.com/gridsync/gridsync/actions/runs/3045400304/jobs/4907659144#step:7:10) -- or any other output for that matter. At first glance, the issue appears to be specific to GitHub Actions' Windows environments, as I was unable to reproduce the issue locally in a Windows 10 VMs (where the PyInstaller-5.4.1-generated executables seemingly run without issue). Further investigation is required...

**Comment by crwood** [comment]
Inspecting the build artifacts created by GHA's Windows runners over several runs shows that, strangely, the PyInstaller bundles contain multiple `python3*.dll` libraries (e.g., a `python310.dll` _and_ a `python39.dll` or a `python310.dll` _and_ a `python37.dll` ) whereas bundles generated locally containing only the expected `python310.dll`. Perhaps this is relevant to the issue?

In addition, removing the extraneous DLL file and attempting to run results in the following:
```
PS C:\Users\vagrant\Gridsync> .\Gridsync-tahoe.exe --version
Traceback (most recent call last):
  File "Lib\site-packages\allmydata\__main__.py", line 16, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "allmydata\scripts\runner.py", line 24, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "allmydata\scripts\debug.py", line 22, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "foolscap\logging\cli.py", line 7, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "foolscap\logging\tail.py", line 7, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "foolscap\api.py", line 16, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "foolscap\pb.py", line 14, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "foolscap\negotiate.py", line 20, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "foolscap\crypto.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "OpenSSL\__init__.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "OpenSSL\crypto.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "cryptography\x509\__init__.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "cryptography\x509\certificate_transparency.py", line 10, in <module>
ImportError: DLL load failed while importing _rust: The specified module could not be found.
``` 

And for Magic-Folder:
```
PS C:\Users\vagrant\Gridsync> .\Gridsync-magic-folder.exe --version                                                                                                                                                                 
Traceback (most recent call last):                                                                                                                                                                                                             
  File "Lib\site-packages\magic_folder\__main__.py", line 5, in <module>                                                                                                                                                                       
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module                                                                                                                                                                    
  File "magic_folder\cli.py", line 52, in <module>                                                                                                                                                                                             
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module                                                                                                                                                                    
  File "magic_folder\client.py", line 47, in <module>                                                                                                                                                                                          
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module                                                                                                                                                                    
  File "magic_folder\web.py", line 7, in <module>                                                                                                                                                                                              
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module                                                                                                                                                                    
  File "nacl\signing.py", line 16, in <module>                                                                                                                                                                                                 
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module                                                                                                                                                                    
  File "nacl\bindings\__init__.py", line 16, in <module>                                                                                                                                                                                       
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module                                                                                                                                                                    
  File "nacl\bindings\crypto_aead.py", line 17, in <module>                                                                                                                                                                                    
ImportError: DLL load failed while importing _sodium: The specified module could not be found.                                                                                                                                                 
[3964] Failed to execute script '__main__' due to unhandled exception!                                                                                                                                                                         
(venv) PS C:\Users\vagrant\tmp\Gridsync>                                                  
```

It remains to be seen whether or not the double-DLL symptom is causally related to the errors seen above. More investigation is required...

**Comment by crwood** [comment]
Seemingly-relevant upstream issue: https://github.com/pyinstaller/pyinstaller/issues/7102
