### ISSUE TITLE
PyInstaller version 5.6.1 breaks GNU/Linux builds due to `ImportError` with libffi.so.6

### ISSUE THREAD

**Issue by crwood** [gridsync/gridsync#579]
The current/latest version of PyInstaller (5.6.1) appears to be [breaking GNU/Linux builds](https://github.com/gridsync/gridsync/actions/runs/3330069099/jobs/5508077493#step:11:42) with the following traceback:

```
Traceback (most recent call last):
  File "gridsync/cli.py", line 12, in <module>
    from gridsync.core import Core
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "gridsync/core.py", line 71, in <module>
    from gridsync.gui import Gui
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "gridsync/gui/__init__.py", line 10, in <module>
    from gridsync.gui.main_window import MainWindow
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "gridsync/gui/main_window.py", line 40, in <module>
    from gridsync.gui.history import HistoryView
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "gridsync/gui/history.py", line 28, in <module>
    from gridsync.gui.status import StatusPanel
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "gridsync/gui/status.py", line 23, in <module>
    from gridsync.magic_folder import MagicFolderStatus
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "gridsync/magic_folder.py", line 31, in <module>
    from gridsync.watchdog import Watchdog
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "gridsync/watchdog.py", line 8, in <module>
    from watchdog.observers import Observer
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "watchdog/observers/__init__.py", line 61, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "watchdog/observers/inotify.py", line 71, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "watchdog/observers/inotify_buffer.py", line 20, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "watchdog/observers/inotify_c.py", line 22, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "ctypes/__init__.py", line 8, in <module>
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
[48129] Failed to execute script 'cli' due to unhandled exception!
```

For what it's worth, `cffi` is already [declared as a hidden import](https://github.com/gridsync/gridsync/blob/904cbd96ddc2f47444a74f926750b49319e4f6e9/pyinstaller.spec#L185) (which _should_ normally result in libffi getting picked up) so I'm not quite sure what's going on here; further investigation is required...

The error does _not_ occur with PyInstaller 5.5.

**Comment by crwood** [comment]
It looks like this should now be fixed by https://github.com/pyinstaller/pyinstaller/pull/7190...
