### ISSUE TITLE
Setuptools >= 66 breaks Magic-Folder PyInstaller builds on Windows

### ISSUE THREAD

**Issue by crwood** [gridsync/gridsync#595]
During a [routine update of dependencies](https://github.com/gridsync/gridsync/compare/main...update-dependencies), PyInstaller-generated Magic-Folder binaries failed to run on Windows with the following traceback:

```
Traceback (most recent call last):
  File "Lib\site-packages\magic_folder\__main__.py", line 5, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "magic_folder\cli.py", line 95, in <module>
  File "appdirs.py", line 196, in user_config_dir
  File "appdirs.py", line 81, in user_data_dir
  File "appdirs.py", line 480, in _get_win_folder_with_pywin32
ImportError: cannot import name 'shellcon' from 'win32com.shell' (D:\a\gridsync\gridsync\dist\Gridsync\win32com\shell\__init__.pyc)
[3216] Failed to execute script '__main__' due to unhandled exception!
```

The PyInstaller-recommended strategy of adding the missing packages (`win32com.shell.shellcon`, `win32com`) to the PyInstaller hidden imports list (alongside the already-existing `win32com.shell` import) does not resolve the issue.

Downgrading/pinning setuptools to 65.7.0 across all environments _does_ appear to prevent the issue from triggering (at the cost of [breaking the NixOS job](https://github.com/gridsync/gridsync/actions/runs/3999786769)...).

Judging by the [setuptools changelog](https://setuptools.pypa.io/en/stable/history.html) in conjunction with the traceback above, the culprit may be related to setuptools' [switch from `appdirs` to `platformdirs`](https://github.com/pypa/setuptools/pull/3769) (which, maybe, conflicts somehow with Magic-Folder's usage of `appdirs`?).

Perhaps there's a way to use the latest setuptools without breaking Magic-Folder PyInstaller builds on Windows?

**Comment by crwood** [comment]
FWIW, a user of the py2exe project [claimed a work around](https://github.com/py2exe/py2exe/issues/175) of adding `pkg_resources._vendor.platformdirs` to their packages list. Sadly, this [did not work](https://github.com/gridsync/gridsync/actions/runs/4000099316/jobs/6864812342) in our (PyInstaller) case.
