### ISSUE TITLE
Sometimes GridSync won't quit

### ISSUE THREAD

**Issue by exarkun** [gridsync/gridsync#609]
Running on NixOS, gridsync 20f8d03efe622d54dc18a2a093b1ec76db8b803b, sometimes after Ctrl-Q and confirming the exit dialog with a "Yes" choice, GridSync keeps running for an indefinite amount of time.

The client where I observe this has 4 grids configured.

* The demo grid, successfully connected.
* The private storage staging grid, successfully connected.
* Two instances of the private storage production grid, not connected.

Before quitting the debug log output is a rapid sequence of "poll Connecting to ..." for the two non-connected grids.  After hitting Ctrl-Q a number of tracebacks appear in the log.  These are attached.
[wontquit.log.txt](https://github.com/gridsync/gridsync/files/10944904/wontquit.log.txt)

**Comment by exarkun** [comment]
On a second Ctrl-Q, sometimes:

```
Traceback (most recent call last):
  File "/home/exarkun/Work/python/gridsync/gridsync/gui/main_window.py", line 575, in confirm_quit
    reactor.stop()  # type: ignore
  File "/nix/store/2zb0dvj2vwqnx4ndva6jr1j6yl74m596-python3-3.9.13-env/lib/python3.9/site-packages/twisted/internet/base.py", line 708, in stop
    raise error.ReactorNotRunning("Can't stop reactor that isn't running.")
twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.
Aborted (core dumped)
```
