### ISSUE TITLE
The CLI is broken on Windows PyInstaller builds

### ISSUE THREAD

**Issue by crwood** [gridsync/gridsync#641]
@hacklschorsch reports that, when attempting to run the Windows PyInstaller build with a CLI flag (e.g., `--help`), the following traceback is shown (in a PyInstaller error dialog):

```
Traceback (most recent call last):
  File "gridsync\cli.py", line 55, in <module>
  File "gridsync\cli.py", line 44, in main
  File "argparse.py", line 1826, in parse_args
  File "argparse.py", line 1859, in parse_known_args
  File "argparse.py", line 2068, in _parse_known_args
  File "argparse.py", line 2008, in consume_optional
  File "argparse.py", line 1936, in take_action
  File "argparse.py", line 1099, in __call__
  File "argparse.py", line 2556, in print_help
  File "argparse.py", line 2562, in _print_message
AttributeError: 'NoneType' object has no attribute 'write'
```

Similarly when attempting to run with `--debug`:

```
Traceback (most recent call last):
  File "gridsync\cli.py", line 55, in <module>
  File "gridsync\cli.py", line 44, in main
  File "gridsync\core.py", line 91, in __init__
  File "gridsync\log.py", line 76, in initialize_logger
  File "twisted\python\log.py", line 642, in startLogging
  File "twisted\python\log.py", line 479, in __init__
AttributeError: 'NoneType' object has no attribute 'write'

```

This happens under both Qt5 and Qt6.

**Comment by crwood** [comment]
Judging by [this comment](https://github.com/pyinstaller/pyinstaller/issues/6244#issuecomment-927131015), it looks like, on Windows, we can either have a "console" (CLI) application or a "windowed" (GUI) application.

One (more involved) solution would be to provide _both_ kinds of executables in the installation and have the "console" executable launch the "windowed" one.

Another (less involved) workaround would be to instruct users to pipe the output elsewhere if/when they need to invoke the CLI via a terminal (e.g., `.\Gridsync.exe | more` -- which prevents the ("windowed") application from detaching and keeps the input/output streams alive).
