### ISSUE TITLE
Standalone `magic-folder` binaries fail due to missing `win32com.shell` import

### ISSUE THREAD

**Issue by crwood** [gridsync/gridsync#707]
As seen in [this failed GitHub Actions job](https://github.com/gridsync/gridsync/actions/runs/11961100669/job/33346577200), "standalone" binaries of `magic-folder` created by PyInstaller with newer versions of Python/PyInstaller will fail to execute with the following error:

```
Traceback (most recent call last):
  File "Lib\site-packages\magic_folder\__main__.py", line 5, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
  File "magic_folder\cli.py", line 92, in <module>
  File "appdirs.py", line 196, in user_config_dir
  File "appdirs.py", line 81, in user_data_dir
  File "appdirs.py", line 480, in _get_win_folder_with_pywin32
ImportError: cannot import name 'shell' from 'win32com.shell' (D:\a\gridsync\gridsync\dist\Gridsync\Magic-Folder\_internal\win32com\shell\__init__.pyc)
[PYI-1476:ERROR] Failed to execute script '__main__' due to unhandled exception!
```

This error does not occur for "merged" builds (i.e., builds in which Gridsync, magic-folder, and Tahoe-LAFS are installed/available under a single python environment); it only occurs when building a `magic-folder` executable via `tox -e pyinstaller-magic-folder` (i.e., a "frozen" environment that does _not_ include Gridsync and Tahoe-LAFS).

Note that `win32com.shell` (and `win32com`) are already included in the PyInstaller "hidden imports" list so it is unclear, at the time of writing, why this dependency isn't being properly detected or included. Further investigation is required...

**Comment by crwood** [comment]
From https://github.com/ActiveState/appdirs:

>Note: This project has been officially deprecated. You may want to check out https://pypi.org/project/platformdirs/ which is a more active fork of appdirs.

**Comment by crwood** [comment]
Ticket filed for deprecated `appdirs` dependency in magic-folder: https://github.com/tahoe-lafs/magic-folder/issues/760

(Note that it's not clear whether magic-folder switching to `platformdirs` will actually resolve _this_ issue, however, since there are potentially other factors -- newer PyInstaller, newer CPython, newer GitHub Actions environments, etc. -- at play here.)

**Comment by crwood** [comment]
Dupe/more info: https://github.com/gridsync/gridsync/issues/595

**Comment by crwood** [comment]
As per [this CI run](https://github.com/gridsync/gridsync/actions/runs/12056817791/job/33620127265), I can confirm that using [a development branch of Magic-Folder](https://github.com/crwood/magic-folder/tree/760.platformdirs) that [replaces `appdirs` with `platformdirs`](https://github.com/tahoe-lafs/magic-folder/pull/761) results in a successful PyInstaller build on Windows.

Once that change lands upstream, we should be able to close this and #595 and remove the Windows-only `setuptools<66` constraint (in `tox.ini`).
